--CREATE TABLE PayRecord (
--    id bigint(20) NOT NULL AUTO_INCREMENT,
--    paymentAmount double(20) NOT NULL,
--    balance double(20) NOT NULL,
--    paymentType varchar(255) NOT NULL,
--    paymentGroup varchar(255) NOT NULL,
--    p_year bigint(20) NOT NULL,
--    p_month bigint(20) NOT NULL,
--    PRIMARY KEY (id)
--    );
--
--CREATE TABLE FileLog (
--    id bigint(20) NOT NULL AUTO_INCREMENT,
--    fileName varchar(255) NOT NULL,
--    numberOfRecords bigint(20) NOT NULL,
--    status varchar(255) NOT NULL,
--    uploadDate timestamp NOT NULL,
--    PRIMARY KEY (id)
--    );
--

--
--DROP TABLE PayRecord;
--DROP TABLE FileLog;